# Generated by Django 3.2.2 on 2021-06-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=64)),
                ('staff_netid', models.CharField(max_length=64, unique=True)),
                ('staff_role', models.CharField(choices=[('online_triage', 'Online Triage'), ('do', 'DO'), ('counsellor', 'Counsellor'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], max_length=32)),
                ('staff_chat_status', models.CharField(choices=[('available', 'Available'), ('away', 'Away'), ('assigned', 'Assigned'), ('chatting', 'Chatting'), ('offline', 'Offline')], max_length=32)),
                ('status_change_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentChatStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_netid', models.CharField(max_length=64, unique=True)),
                ('chat_request_time', models.DateTimeField(auto_now=True, null=True)),
                ('student_chat_status', models.CharField(choices=[('waiting', 'Waiting'), ('chatting', 'Chatting'), ('assigned', 'Assigned'), ('end', 'End')], max_length=32)),
                ('chat_start_time', models.DateTimeField(default=None, null=True)),
                ('chat_end_time', models.DateTimeField(default=None, null=True)),
                ('assigned_counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.staffstatus')),
            ],
        ),
    ]
